### ISSUE TITLE
the number of the manipulated variables

### ISSUE THREAD

**Issue by SherleyC** [camaramm/tennessee-eastman-profBraatz#1]
According to Downs and Vogel(1993),the number of process manipulated variables is 12.But in this dataset,the number is 11.Want to know which XMV you choose to delete?Besides,how to set the 21th fault?

**Comment by camaramm** [comment]
Hi @SherleyC.

The dataset was made available without editing, i.e., I didn't delete any XMV.
Maybe you'd like to check the [original web page](https://web.archive.org/web/20091010114800/http://brahms.scs.uiuc.edu:80/lssrl/software/TE_process/) (from the Internet Archive).

About setting the 21th fault, I haven't tried it.

Maybe this repository can help you: https://github.com/gmxavier/TEP-meets-LSTM; there is an R interface to the code.

**Comment by camaramm** [comment]
Hi @SherleyC .

According to the code, the manipulated variable XMV(12) is "Agitator Speed" (`teprob.f`, line 107).
Inspecting the code of `temain_mod.f`, you will see that XMV(12) does not affect any control algorithm.
So, I think that the agitator speed is the answer, assuming variables' description is accurate.

In spite of the text in line 101 of `temain_mod.f`, stating 21 programmed disturbances, the declaration of IDV variable is IDV(20).
In addition, `teprob.f` ends process disturbances description in line 191 for IDV(20). So I believe the program will throw an error if one try to set IDV with length 21.
