### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by JsonJsons** [camaramm/tennessee-eastman-profBraatz#3]
How do you use this model to get more TE data?  I just started learning the TE model, and  I don’t understand very well.You know that the TE model on the University of Washington has 28 faults. How do I set the fault code?  After setting the fault to fault 6, it can only run for a while, then it can't run. Why is this?
                                                                           Thank you！

**Comment by camaramm** [comment]
Hello @JsonJsons 

Maybe you'd like to check the [original web page](https://web.archive.org/web/20091010114800/http://brahms.scs.uiuc.edu:80/lssrl/software/TE_process/) (from the Internet Archive).

Considering you've just started learning, this repository may be useful for you: https://github.com/gmxavier/TEP-meets-LSTM; there is an R interface to the code.
