### ISSUE TITLE
Universal Gas Constant (R) unit

### ISSUE THREAD

**Issue by ldariva** [camaramm/tennessee-eastman-profBraatz#6]
Hi,
I am studying this model and I am strugling to understand what is the unit of R (Universal Gas Constant). In the code its value is set to 998,9. I tried different combinations of unit os pressure and volume but wasn't able to find one that give this value. 
What it the unit for this constant?
Thanks

**Comment by camaramm** [comment]
Hi. Sorry, I'm not able to help you on this question. Have you checked the reference papers? Maybe they can help on this issue.

**Comment by ldariva** [comment]
Yes. I have checked a lot of references to this model but was not able to find the origin of this value. 
Well, thanks anyway.

**Comment by camaramm** [comment]
Is this the only piece of code where R is defined?
https://github.com/camaramm/tennessee-eastman-profBraatz/blob/0643318858ce7c87292bd59820b459e12a13d009/teprob.f#L475

**Comment by camaramm** [comment]
R = 998.9 mm Hg, ft³, lb-mole, °K
ref: https://www.mitchellscientific.com/emHelp/index.html?conversionunits.htm

**Comment by ldariva** [comment]
Wow!!! Thank you very much!!!
